// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Db9U04ZlP0T1u7l5pOpt77Ovc9VnRhY',
    appId: '1:862899879191:web:c4aab0d66c824374f4cb52',
    messagingSenderId: '862899879191',
    projectId: 'todolist-3f079',
    authDomain: 'todolist-3f079.firebaseapp.com',
    storageBucket: 'todolist-3f079.firebasestorage.app',
    measurementId: 'G-XCBZ5ML2X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9RUHldLHknZr5kW5YWm5ELY6dP4_j0uo',
    appId: '1:862899879191:android:dfb7990a585aa719f4cb52',
    messagingSenderId: '862899879191',
    projectId: 'todolist-3f079',
    storageBucket: 'todolist-3f079.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwAZtLxOgrvI7uUElVuI1zma27qmtSI1I',
    appId: '1:862899879191:ios:0c7b515df198b9eff4cb52',
    messagingSenderId: '862899879191',
    projectId: 'todolist-3f079',
    storageBucket: 'todolist-3f079.firebasestorage.app',
    iosBundleId: 'com.krish.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwAZtLxOgrvI7uUElVuI1zma27qmtSI1I',
    appId: '1:862899879191:ios:0c7b515df198b9eff4cb52',
    messagingSenderId: '862899879191',
    projectId: 'todolist-3f079',
    storageBucket: 'todolist-3f079.firebasestorage.app',
    iosBundleId: 'com.krish.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6Db9U04ZlP0T1u7l5pOpt77Ovc9VnRhY',
    appId: '1:862899879191:web:a6d01f6de0d048f5f4cb52',
    messagingSenderId: '862899879191',
    projectId: 'todolist-3f079',
    authDomain: 'todolist-3f079.firebaseapp.com',
    storageBucket: 'todolist-3f079.firebasestorage.app',
    measurementId: 'G-RDLT69F7X6',
  );
}
